server:  port: 8084
spring:  application:    name:  SECURITY-SERVICE
eureka:
  client:
    eureka-server-port: 8761
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhostlogging:  level:    com: INFO